apiVersion: v1
kind: Secret
metadata:
  name: nacos-auth
  namespace: nacos
  labels:
    app: nacos
type: Opaque
data:
  auth-token: YndhK1RxeVRYVUUxdzhPOEFBK2lsWnFSc1NkR3plcDM2bXB1VlQxUlo4dz0=
  identity-key: bmFjb3MtaWQtOGM4NWI1ZDI=
  identity-value: c3JpREMxMWRaSGFYZ3Jod2RWMlBhMnNHY3BCczkrc1Y=
